### ISSUE TITLE
Could not find latest version

### ISSUE THREAD

**Issue by abjoker** [mfreeborn/fastapi-sqlalchemy#16] opened 2020-07-21 07:06 UTC
Hi!

While adding the latest version of the package to requirements.txt, I get the following error
```
ERROR: Could not find a version that satisfies the requirement FastAPI-SQLAlchemy==0.1.4 
```
Also doing a simple pip install gives version ```0.1.0``` instead of ```0.1.4```

I require the latest version(0.1.4) since 0.1.0 does not support starlette-0.13.4

Please help.
Thank You

**Comment by mfreeborn** [comment] 2020-07-28 20:51
And what version do you see on [PyPI](https://pypi.org/project/FastAPI-SQLAlchemy/)?

I've just issued a patch release, any combination of `pip install ...`: `fastapi_sqlalchemy`, `fastapi_sqlalchemy==0.1.5`, FastApi-SQLAlchemy` and `FastApi-SQLAlchemy==0.1.5` gets version 0.1.5.

**Comment by mfreeborn** [comment] 2020-08-18 16:07
Closing as unable to reproduce error and no further input from thread starter.

**Closed by mfreeborn** 2020-08-18 16:07 UTC
