### ISSUE TITLE
ERROR: fastapi-sqlalchemy 0.1.0 has requirement starlette<=0.12.9,>=0.12.9, but you'll have starlette 0.13.4 which is incompatible.

### ISSUE THREAD

**Issue by cnly1987** [mfreeborn/fastapi-sqlalchemy#14] opened 2020-06-17 02:43 UTC
if i install starlette<=0.12.9
then fastapi  error:
from starlette.concurrency import run_until_first_complete  # noqa
ImportError: cannot import name 'run_until_first_complete'

**Comment by mfreeborn** [comment] 2020-06-17 06:23
Thanks for raising this. Can I first ask you to update to the latest version of fastapi-sqlalchemy (0.1.4 at time of writing) and then tell me if you get the same error? Looking back, I think I messed up the Starlette version requirements in 0.1.0.

**Comment by cnly1987** [comment] 2020-06-17 15:38
> Thanks for raising this. Can I first ask you to update to the latest version of fastapi-sqlalchemy (0.1.4 at time of writing) and then tell me if you get the same error? Looking back, I think I messed up the Starlette version requirements in 0.1.0.

yeah!  
fastapi's lastest-version depends Starlette=0.13.4   
but the  fastapi-sqlalchemy_0.1.0 depends  Starlette=0.12.9
Starlette(0.13.4)   no module named 'run_until_first_complete'

**Comment by mfreeborn** [comment] 2020-06-18 09:26
Hi @cnly1987 - can I just check why you closed this? If this is resolved, then I don't need to look into it, otherwise I will look into it.

**Comment by nahid002345** [comment] 2020-06-21 14:53
@mfreeborn I have installed the latest version of fastapi-sqlalchemy, but still it's starlette version error!

**Comment by mfreeborn** [comment] 2020-06-21 16:31
Reopened and will fix tomorrow. Thanks for the feedback.

**Comment by mfreeborn** [comment] 2020-06-22 10:40
@nahid002345 I'm struggling to reproduce on my end. I've done a fresh install of fastapi and fastapi-sqlalchemy and they seem to work fine together. Fastapi-sqlalchemy requires starlette >= 0.12.9, which is compatible with fastapi's requirement  starlette == 0.13.4.

If you type `pip list`, what is the output?

**Comment by mfreeborn** [comment] 2020-07-28 19:56
No responses and unable to reproduce. Closing.

**Closed by mfreeborn** 2020-07-28 19:56 UTC
